const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],money=n=>Store.formatNaira(n);
function guard(){if(!Store.isAdmin()&&!location.pathname.endsWith('/admin/')&&!location.pathname.endsWith('/admin/index.html'))location.href='../index.html'}
function login(){const f=$('#admin-login');if(!f)return;f.onsubmit=e=>{e.preventDefault();if(f.email.value==='afolyvickie08@gmail.com'&&f.password.value==='admin123'){Store.setAdminSession(true);location.href='dashboard.html'}else alert('Invalid demo login.')}}
function nav(){$$('.logout').forEach(o=>o.onclick=()=>{Store.logoutAdmin();location.href='index.html'})}
async function stats(){if(!$('[data-stat]'))return;const o=await Store.getOrders(),p=await Store.getProducts(),v={pending:o.filter(x=>x.status==='Pending').length,submitted:o.filter(x=>x.status==='Payment submitted').length,confirmed:o.filter(x=>x.status==='Confirmed').length,products:p.length};Object.entries(v).forEach(([k,n])=>{const e=$(`[data-stat="${k}"]`);if(e)e.textContent=n})}
async function orders(){const b=$('#orders-body');if(!b)return;b.innerHTML='<tr><td colspan="7">Loading…</td></tr>';const list=await Store.getOrders();b.innerHTML=list.map(o=>`<tr><td><b>${o.id}</b></td><td>${o.customer.name}<br>${o.customer.email}<br>${o.customer.phone||''}</td><td>${o.items.map(i=>i.name+' × '+i.qty).join('<br>')}</td><td>${money(o.total)}</td><td><span class="badge">${o.status}</span></td><td>${o.receipt?'<img class="receipt-thumb" src="'+o.receipt+'">':'—'}</td><td><a class="pill pill-ghost small-pill" href="order.html?id=${o.id}">Open</a></td></tr>`).join('')||'<tr><td colspan="7">No orders yet.</td></tr>'}
async function order(){const e=$('#order-detail');if(!e)return;e.innerHTML='<p>Loading…</p>';const o=await Store.getOrder(new URLSearchParams(location.search).get('id'));if(!o){e.innerHTML='<p>Order not found.</p>';return}e.innerHTML=`<div class="admin-card glass"><span class="eyebrow">${o.id}</span><h1 class="serif">Order detail</h1><p><b>${o.customer.name}</b><br>${o.customer.email}<br>${o.customer.phone||''}<br>${o.fulfilment==='delivery'?'Delivery: '+o.customer.address:'Pickup at Yidi Gate, Ibadan'}</p><h3 class="serif">Items</h3>${o.items.map(i=>`<div class="order-line"><span>${i.name} × ${i.qty}</span><b>${money(i.line)}</b></div>`).join('')}<div class="order-line"><span>Charges</span><b>${money(o.charges)}</b></div><div class="order-line"><span>Delivery</span><b>${money(o.delivery)}</b></div><div class="order-line order-total"><span>Total</span><b>${money(o.total)}</b></div><h3 class="serif">Receipt</h3>${o.receipt?'<img src="'+o.receipt+'" class="admin-receipt">':'<div class="notice">No receipt uploaded.</div>'}<div class="field"><label>Status</label><select id="status"><option>Pending</option><option>Payment submitted</option><option>Under verification</option><option>Confirmed</option><option>Processing</option><option>Completed</option><option>Cancelled</option></select></div><button id="save-status" class="pill pill-primary">Save status</button></div>`;$('#status').value=o.status;$('#save-status').onclick=async()=>{const btn=$('#save-status');btn.disabled=true;btn.textContent='Saving…';await Store.updateOrder(o.id,{status:$('#status').value});location.reload()}}
async function products(){const b=$('#products-body');if(!b)return;b.innerHTML='<tr><td colspan="4">Loading…</td></tr>';const list=await Store.getProducts();b.innerHTML=list.map(p=>`<tr><td><img src="${p.image}" class="receipt-thumb"></td><td>${p.name}</td><td>${money(p.price)}</td><td><a class="pill pill-ghost small-pill" href="product-edit.html?id=${p.id}">Edit</a> <button class="pill pill-ghost small-pill del" data-id="${p.id}">Delete</button></td></tr>`).join('')||'<tr><td colspan="4">No products yet.</td></tr>';$$('.del').forEach(x=>x.onclick=async()=>{if(confirm('Delete this product?')){await Store.deleteProduct(x.dataset.id);products()}})}
async function productForm(){const f=$('#product-form');if(!f)return;const id=new URLSearchParams(location.search).get('id');const p=id?await Store.getProduct(id):null;if(p){f.name.value=p.name;f.price.value=p.price;f.category.value=p.category;f.description.value=p.description;f.current.value=p.image}f.onsubmit=async e=>{e.preventDefault();const btn=f.querySelector('button');const original=btn.textContent;btn.disabled=true;btn.textContent='Saving…';const file=f.image.files[0];await Store.saveProduct({id:id||undefined,name:f.name.value,price:+f.price.value,category:f.category.value,description:f.description.value,image:f.current.value},file);location.href='products.html'}}
document.addEventListener('DOMContentLoaded',()=>{guard();login();nav();stats();orders();order();products();productForm()});
